-- Data Base for MySQL 5.*.* 
-- Made in MySQL Workbench Win64
-- Host 127.0.0.1 DataBase: farmacia

-- Hecha por:
-- Eduardo
-- Diego
-- Raul

DROP DATABASE IF EXISTS `farmacia`;

CREATE DATABASE `farmacia`;

USE farmacia;

DROP TABLE IF EXISTS `empleados`;

CREATE TABLE `empleados` (
  `DNI` VARCHAR(9) NOT NULL ,
  `CONTRASENIA` varchar(45) NOT NULL,
  `NOMBRE` varchar(45) NOT NULL,
  `FECHA_CONTRATACION` date NOT NULL,
  `ADMIN` BIGINT(2) NOT NULL,
  PRIMARY KEY (`DNI`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `almacen`;

CREATE TABLE `almacen` (
  `ID_ALMACEN` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `NOMBRE_ALMACEN` varchar(45) NOT NULL UNIQUE,
  `CANTIDAD` BIGINT(20) NOT NULL,
  PRIMARY KEY (`ID_ALMACEN`)
) ENGINE=InnoDB DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `ventas`;

CREATE TABLE `ventas` (
  `ID_VENTA` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `FECHA_VENTA` date NOT NULL,
  `TOTAL_VENTA` BIGINT(20) NOT NULL,
  `DNI` VARCHAR(9) NOT NULL ,
  PRIMARY KEY (`ID_VENTA`),
  KEY `EMPLEADO_FK_idx` (`DNI`),
  CONSTRAINT `EMPLEADO_FK` FOREIGN KEY (`DNI`) REFERENCES `empleados` (`DNI`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;

DROP TABLE IF EXISTS `almacenventa`;

CREATE TABLE `almacenventa` (
  `ID_ALMACENVENTA` BIGINT(20) NOT NULL AUTO_INCREMENT,
  `ID_ALMACEN` BIGINT(20),
  `ID_VENT` BIGINT(20),
  PRIMARY KEY (`ID_ALMACENVENTA`),
  KEY `ALMACEN_FK_idx` (`ID_ALMACEN`),
  CONSTRAINT `ALMACEN_FK` FOREIGN KEY (`ID_ALMACEN`) REFERENCES `almacen` (`ID_ALMACEN`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  KEY `VENTAS_FK_idx` (`ID_VENT`),
  CONSTRAINT `VENTAS_FK` FOREIGN KEY (`ID_VENT`) REFERENCES `ventas` (`ID_VENTA`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=1 DEFAULT CHARSET=UTF8;